{{- /*
Deploys a database client, service, and ingress.
*/ -}}

{{- if .Values.extensions.dbClient.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bitwarden.dbClient" . }}
  namespace: {{ .Release.Namespace }}
  annotations: {{ toYaml .Values.extensions.dbClient.annotations | nindent 4 }}
  labels:
    app: {{ template "bitwarden.dbClient" . }}
    app.kubernetes.io/component: db-client
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "bitwarden.dbClient" . }}
  template:
    metadata:
      labels:
        app: {{ template "bitwarden.dbClient" . }}
    spec:
      containers:
        - name: db-client
          image: "{{ .Values.extensions.dbClient.image.name }}:{{ .Values.extensions.dbClient.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.extensions.dbClient.service.port }}
          env:
            - name: CB_SERVER_NAME
              value: {{ template "bitwarden.dbClient" . }}
            - name: CB_SERVER_URL
              value: "db.{{ .Values.general.domain }}"
          envFrom:
            - secretRef:
                name: {{ template "bitwarden.dbClient" . }}-secret
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitwarden.dbClient" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bitwarden.dbClient" . }}
    app.kubernetes.io/component: db-client
spec:
  selector:
    app: {{ template "bitwarden.dbClient" . }}
  ports:
    - port: {{ .Values.extensions.dbClient.service.port }}
      targetPort: {{ .Values.extensions.dbClient.service.port }}


{{- if .Values.general.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "bitwarden.dbClient" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    {{- if .Values.argoCDSupport }}
    link.argocd.argoproj.io/environment: "Go to DB Client|https://db.{{ .Values.general.domain }}"
    {{- end }}
    {{- if .Values.general.ingress.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.general.ingress.tls.clusterIssuer }}
    {{- end }}
  labels:
    app.kubernetes.io/component: ingress
{{ include "bitwarden.labels" . | indent 4 }}
spec:
  ingressClassName: {{ .Values.general.ingress.className }}
  rules:
    - host: db.{{ .Values.general.domain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "bitwarden.dbClient" . }}
                port: 
                  number: {{ .Values.extensions.dbClient.service.port }}
  tls:
    - hosts:
      - db.{{ .Values.general.domain }}
      {{- if .Values.general.ingress.tls.name }}
      secretName: {{ .Values.general.ingress.tls.name }}-db-client
      {{- end }}
{{- end }}
{{- end }}
