# Publishes the URI endpoints for the environment to a comment of the GitHub pull request.
---
kind: Job
apiVersion: batch/v1
metadata:
  name: "{{ .Release.Name }}-publish-endpoints-github"
  labels:
    app.kubernetes.io/component: post-install-publish-endpoints
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- if .Values.argoCDSupport }}
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    {{- end }}
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-publish-endpoints-github"
      labels:
        app.kubernetes.io/component: post-install-publish-endpoints
    spec:
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: "{{ .Values.serviceAccount.name }}"
      {{- end }}
      restartPolicy: Never
      containers:
        - name: publish-endpoints
          image: "{{ .Values.supportComponents.kubectl.image.name }}:{{ .Values.supportComponents.kubectl.image.tag }}"
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              # Comment data
              comment_body=$(cat <<EOF
              Ephemeral Environment Details:
              Web: [{{ template "bitwarden.endpoint.web" . }}]({{ template "bitwarden.endpoint.web" . }})
              Api: [{{ template "bitwarden.endpoint.api" . }}]({{ template "bitwarden.endpoint.api" . }})
              EOF
              )

              # Escape newlines and special characters
              comment_body=$(echo "$comment_body" | jq -sR .)
              
              # Create a comment if we haven't already
              if [ -z "$(kubectl get configmap {{ .Release.Name }}-pr-comment-id -o jsonpath='{.data.comment_id}')" ]; then
                # Post comment
                echo "Creating comment on PR ${GITHUB_PR_ID}"

                while true; do
                  RESPONSE=$(curl -s -D - -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "Accept: application/json" \
                  -d "{\"body\": $comment_body}" \
                  "https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_PROJECT}/issues/${GITHUB_PR_ID}/comments")
                  
                  HTTP_STATUS=$(echo "$RESPONSE" | grep HTTP | awk '{print $2}')
                  RATE_LIMIT_REMAINING=$(echo "$RESPONSE" | grep -i 'x-ratelimit-remaining:' | awk '{print $2}')
                  RATE_LIMIT_RESET=$(echo "$RESPONSE" | grep -i 'x-ratelimit-reset:' | awk '{print $2}')
                  RESPONSE_BODY=$(echo "$RESPONSE" | sed -n '/^\r$/,$p' | jq)
                  
                  echo "HTTP Status: $HTTP_STATUS"
                  echo "Rate Limit Remaining: $RATE_LIMIT_REMAINING"
                  echo "Response: $RESPONSE_BODY"

                  if [[ "$HTTP_STATUS" == "201" ]]; then
                    # Get comment ID and save it to configmap
                    COMMENT_ID=$(echo "$RESPONSE_BODY" | grep -o '"id": [0-9]*' | awk '{print $2}' | head -n 1)
                    kubectl create configmap {{ .Release.Name }}-pr-comment-id --from-literal=comment_id=${COMMENT_ID}
                    break
                  elif [[ "$HTTP_STATUS" == "403" || "$HTTP_STATUS" == "429" ]]; then
                    CURRENT_TIME=$(date +%s)
                    SLEEP_TIME=$((RATE_LIMIT_RESET - CURRENT_TIME))
                    echo "Rate limit exceeded, waiting ${SLEEP_TIME} seconds until reset..."
                    sleep $SLEEP_TIME
                  else
                    echo "Received error from GitHub, retrying in 5 minutes..."
                    sleep 300
                  fi
                done

                echo "Comment URL: https://github.com/${GITHUB_OWNER}/${GITHUB_PROJECT}/issues/${GITHUB_PR_ID}#issuecomment-${COMMENT_ID}"
              fi
          envFrom:
            - secretRef:
                name: {{ template "bitwarden.sharedCloudResourcesSecret" . }}
            - configMapRef:
                name: {{ .Release.Name }}-config-map
