{{- if not .Values.argoCDSupport }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-cleanup"
  labels:
    app.kubernetes.io/component: post-delete-hook
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation

spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-cleanup"
      labels:
        app.kubernetes.io/component: post-delete-hook
    spec:
    {{- if .Values.serviceAccount.name }}
      serviceAccountName: "{{ .Values.serviceAccount.name }}"
    {{- end }}
      containers:
      - name: delete-resources
        command: [
          "/bin/sh", "-c"
        ]
        args: ['
          kubectl delete configmap {{ .Release.Name }}-config-map -n {{ .Release.Namespace }};
          kubectl delete configmap {{ .Release.Name }}-config-map-web -n {{ .Release.Namespace }};
          {{- if .Values.component.keyConnector.enabled }}
          kubectl delete configmap {{ .Release.Name }}-config-map-key-connector -n {{ .Release.Namespace }};
          {{- end }}
          {{- if .Values.database.enabled }}
          kubectl delete secret "{{ .Release.Name }}-sql-connection-string" -n {{ .Release.Namespace }};
          {{- end }}
          kubectl delete secret {{ .Release.Name }}-identity-cert -n {{ .Release.Namespace }};
          kubectl delete secret {{ .Release.Name }}-identity-cert-password  -n {{ .Release.Namespace }};
          {{- if eq .Values.component.keyConnector.config.rsaKeyProvider "certificate" }}
          kubectl delete secret {{ .Release.Name }}-key-connector-cert -n {{ .Release.Namespace }};
          kubectl delete secret {{ .Release.Name }}-key-connector-cert-password -n {{ .Release.Namespace }};
          {{- end }}
          kubectl delete job {{ .Release.Name }}-setup;
          kubectl delete job {{ .Release.Name }}-migrator;
          {{- if .Values.component.keyConnector.enabled }}
          kubectl delete job {{ .Release.Name }}-key-connector-setup -n {{ .Release.Namespace}};
          {{- end }}
          echo "Done"
        ']
        image: "{{ .Values.supportComponents.kubectl.image.name }}:{{ .Values.supportComponents.kubectl.image.tag }}"
      restartPolicy: Never
{{- end }}