# Get tag from image.tag, or coreVersionOverride, or default to coreVersionDefault
{{- $tag := default ( default ( include "bitwarden.coreVersionDefault" nil ) .Values.general.coreVersionOverride ) .Values.supportComponents.dbMigrator.image.tag -}}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-pre-upgrade"
  labels:
    app.kubernetes.io/component: pre-install-db-migrator-job
  annotations:
    {{- if .Values.database.enabled }}
    "helm.sh/hook": pre-upgrade
    {{- if .Values.argoCDSupport }}
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,BeforeHookCreation
    {{ end }}
    {{- else }}
    "helm.sh/hook": pre-install,pre-upgrade
    {{- end }}
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-db-pre-upgrade"
      labels:
        app.kubernetes.io/component: pre-install-db-migrator-job
    spec:
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      {{- end }}
      containers:
      - name: migrate-db
        env:
        - name: MSSQL_CONN_STRING
          valueFrom:
            secretKeyRef:
              {{- if .Values.database.enabled }}
              name: {{ .Release.Name }}-sql-connection-string
              {{- else }}
              name: {{ .Values.secrets.secretName | quote }}
              {{- end }}
              key: globalSettings__sqlServer__connectionString
        image: "{{ .Values.supportComponents.dbMigrator.image.name }}:{{ $tag }}"
        volumeMounts:
        {{- if .Values.secrets.secretProviderClass }}
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        {{- end }}
      restartPolicy: Never
      volumes:
        {{- if .Values.secrets.secretProviderClass }}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secrets.secretProviderClass }}
        {{- end }}
