{{- if .Values.featureFlags }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-feature-flags
data:
  flags.json: |
    {
      "flagValues": {
        {{- $first := true }}
        {{- range $key, $value := .Values.featureFlags }}
          {{- if not $first }},{{ end }}
          "{{ $key }}": {{ $value | quote }}
          {{- $first = false }}
        {{- end }}
      }
    }
{{- end }}
