featureFlags:
  generator-tools-modernization: true
component:
  admin:
    image:
      name: bitwardenprod.azurecr.io/admin
      tag: BRE-demo-ee-01@sha256:5acbf0aa70581934cd6fcfc88cac27b8cf1f5814a6cd24afe560fbd229a06fa5
  api:
    image:
      name: bitwardenprod.azurecr.io/api
      tag: BRE-demo-ee-01@sha256:9ecdf534b7c35fbcb3e7d27462a2adf44bc399d7091c30c5b632bd2ac7c6a8ae
  attachments:
    image:
      name: bitwardenprod.azurecr.io/attachments
      tag: BRE-demo-ee-01@sha256:4eac2312f090f8ca5fa161126446df8afa422806a91c0806a897acd2c12679ae
  events:
    image:
      name: bitwardenprod.azurecr.io/events
      tag: BRE-demo-ee-01@sha256:9857fbffba2fd2048d17138cbc9e2a46cbdf74ae41bdcf1d48353787ecff85ab
  icons:
    image:
      name: bitwardenprod.azurecr.io/icons
      tag: BRE-demo-ee-01@sha256:5c16534def8bc9ba393927ecd6698a3575e495718cad0fe761a251722f5bce76
  identity:
    image:
      name: bitwardenprod.azurecr.io/identity
      tag: BRE-demo-ee-01@sha256:bc4afa1a92f48d43b92f3fff173e76c6937e800e918328b648cb27d37b4e17da
  notifications:
    image:
      name: bitwardenprod.azurecr.io/notifications
      tag: BRE-demo-ee-01@sha256:8664cf346b66a9d15aaf31c25987c6726bfffca9d8ddf5b9307159f40a8fe5cf
  scim:
    image:
      name: bitwardenprod.azurecr.io/scim
      tag: BRE-demo-ee-01@sha256:f36a3ae873568d93afa2d70256a3c3aa6e0f8e0eba8c91319ee74eb0a3b4e749
  sso:
    image:
      name: bitwardenprod.azurecr.io/sso
      tag: BRE-demo-ee-01@sha256:716f80541a8770408c963daba7341f9523d1427ce8ac28b33f0d65fc96086410
supportComponents:
  dbMigrator:
    image:
      name: bitwardenprod.azurecr.io/mssqlmigratorutility
      tag: BRE-demo-ee-01@sha256:32ba3a2a94ce5c4d6ff67a8ae05aad78a606bd097ceb5eaaac01615498d1a963
