apiVersion: v2
<<<<<<< HEAD
appVersion: 2025.3.3
=======
appVersion: 2025.7.3
>>>>>>> upstream/main
description: A Helm chart for deploying a Bitwarden instance on Kubernetes
home: https://github.com/bitwarden/helm-charts/tree/main/charts/self-host
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/icon-square.svg
maintainers:
- name: bitwarden
name: self-host
type: application
<<<<<<< HEAD
version: 2025.3.1
=======
version: 2025.7.3
>>>>>>> upstream/main
