name: Branch Cleanup

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight

jobs:
  cleanup:
    name: Cleanup Unused Branches
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      # Check out the current repository
      - name: Check out ephemeral-environment-charts repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Clone the relevant repositories
      - name: Checkout server repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: server
          repository: bitwarden/server
          fetch-depth: 0

      # Run the shell script to compare branches and delete unused ones
      - name: Cleanup branches
        run: |
          chmod +x scripts/cleanup_branches.sh
          ./scripts/cleanup_branches.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

