name: Branch Cleanup

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight

jobs:
  cleanup:
    name: Cleanup Unused Branches
    runs-on: ubuntu-24.04

    steps:
      # Check out the current repository
      - name: Check out ephemeral-environment-charts repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Clone the relevant repositories
      - name: Checkout server repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: server
          repository: bitwarden/server
          fetch-depth: 0

      - name: Clone billing relay repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: billing-relay
          repository: bitwarden/billing-relay
          fetch-depth: 0

      # Run the shell script to compare branches and delete unused ones
      - name: Cleanup branches
        run: |
          chmod +x cleanup_branches.sh
          ./cleanup_branches.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

