name: Upstream Sync

on:
  schedule:
    # Daily at 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    #   pull-requests: write
    #   issues: write
    #   id-token: write
    env:
      _UPSTREAM_REPO: bitwarden/helm-charts
      _UPSTREAM_BRANCH: main
      _TARGET_BRANCH: main
    steps:
    #   - name: Log in to Azure
    #     uses: bitwarden/gh-actions/azure-login@main
    #     with:
    #       subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #       tenant_id: ${{ secrets.AZURE_TENANT_ID }}
    #       client_id: ${{ secrets.AZURE_CLIENT_ID }}

    #   - name: Retrieve secrets
    #     id: retrieve-secrets
    #     uses: bitwarden/gh-actions/get-keyvault-secrets@main
    #     with:
    #       keyvault: "bitwarden-ci"
    #       secrets: "github-pat-bitwarden-devops-bot-repo-scope"

    #   - name: Log out from Azure
    #     uses: bitwarden/gh-actions/azure-logout@main

    #   - name: Checkout repository
    #     uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    #     with:
    #       fetch-depth: 0
    #       token: ${{ steps.retrieve-secrets.outputs.github-pat-bitwarden-devops-bot-repo-scope }}

    #   - name: Configure Git
    #     run: |
    #       git config --global user.name "github-actions[bot]"
    #       git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - uses: tgymnich/fork-sync@v1.8
      with:
        owner: bitwarden
        base: main
        head: main